### PR TITLE
fix: Extension is not switched to new account after creating it

### LINKED ISSUE #1348: Extension is not switched to new account after creating it
I think we briefly discussed this before. To me it doesn't look like a race condition but it's a persistent issue, that causes quite some confusion in demos (and presumably also for actual users).

### PR DESCRIPTION
**Pull request by juliopavila**
## **Description:**  

Closes #1348
This PR addresses a persistent UX issue described in #1348, where the extension would not switch to the newly created account after the user completed the creation flow.

### Context  
The problem was caused by missing handling in `useLaunchRoute` for the case where a new route is created (i.e. the `routeId` differs from the current `activeRouteId`). While the `onLaunch` callback was invoked, no navigation was triggered, leaving the extension and UI in an inconsistent state.

### Changes  
- Updated `useLaunchRoute` to differentiate between updating an existing account vs. creating a new one.
- When a new route is detected, we now:
  - Invoke the `onLaunch` callback (as before),
  - Immediately navigate to the corresponding route.
- For existing routes with pending transactions, we preserve the existing behavior and prompt for user confirmation.

### CODE REVIEW

File: deployables/extension/src/panel/pages/useLaunchRoute.ts [hunk 1]
```diff
@@ -14,45 +14,48 @@ export const useLaunchRoute = ({ onLaunch }: OnLaunchOptions = {}) => {
...
+      if (activeRouteId == null || activeRouteId !== routeId) {
+        if (onLaunchRef.current) {
+          onLaunchRef.current(routeId, tabId)
+        }
 
-        if (transactions.length > 0 && activeRoute.avatar !== newRoute.avatar) {
-          setPendingRouteId(routeId)
+        navigate(`/${routeId}`)
+        return
+      }
```
Comment (frontendphil) [inline deployables/extension/src/panel/pages/useLaunchRoute.ts:30]: This will immediately launch a route without asking to clear transactions. If you keep the existing logic, but move the `navigate` call to the end of this method (after `onLaunchRef.current` was invoked) it would fix our issue with just one line.

Comment (frontendphil) [reply deployables/extension/src/panel/pages/useLaunchRoute.ts:30]: It would also be great if you could cover this scenario with a test case.

File: deployables/extension/src/panel/pages/useLaunchRoute.ts [hunk 2]
```diff
@@ -27,32 +26,34 @@ export const useLaunchRoute = ({ onLaunch }: OnLaunchOptions = {}) => {
...
 
       if (onLaunchRef.current != null) {
         onLaunchRef.current(routeId, tabId)
       }
+
+      if (activeRouteId == null || activeRouteId !== routeId) {
+        navigate(`/${routeId}`)
+      } else {
+        navigate(`/${activeRouteId}/clear-transactions/${routeId}`)
+      }
```
Comment (frontendphil) [inline deployables/extension/src/panel/pages/useLaunchRoute.ts:41]: This case should never happen. This would mean we're clearing transactions without the consent of the user. However, if we reach this point of the code, we can keep all transactions even if we switch the route because the target safe stays the same, or there are no transactions to clear. So `navigate(`/${routeId})` is the only viable option.
