### PR TITLE
fix: wrong route used when creating a new one

### LINKED ISSUE #259: Pilot uses the wrong route to fetch modules when creating a new route configuration
**Describe the bug**
Pilot seems to use either the currently active or a default route configuration to fetch modules when a new route configuration is being created.

**To Reproduce**

1. Add new route
2. Select chain `Arbitrum One`
3. Select piloted account `0x5a064eC22bf46dfFAb8a23b52a442FC98bBBD0Fb`

**Expected behavior**
The app should use `https://airlock.gnosisguild.org/api/v1/42161/rpc` to fetch modules. However, it uses `https://airlock.gnosisguild.org/api/v1/1/rpc`

### PR DESCRIPTION
**Pull request by frontendphil**
Fixes #259 

`useZodiacMod` would use the `avatar` from a default route instance when creating a new route. I've changed the hook to operate solely on the `safeAddress` that was passed to it (which incidentally also is the avatar).

### CODE REVIEW

File: extension/src/panel/integrations/zodiac/useZodiacModules.ts [hunk 1]
```diff
@@ -27,37 +27,35 @@ interface Module {
...
-        console.error(`Could not fetch modules of Safe ${safeAddress}`, e)
+        console.error(`Could not fetch modules of Safe ${address}`, e)
         setError(true)
       })
       .finally(() => setLoading(false))
-  }, [chainId, safeAddress])
+  }, [address, chainId])
 
-  if (!validateAddress(safeAddress) || error) {
+  if (!validateAddress(address) || error) {
```
Comment (jfschwarz) [inline extension/src/panel/integrations/zodiac/useZodiacModules.ts:50]: This is obsolete. `parsePrefixedAddress` would already throw if `address` were invalid
